<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ActivitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('activities')->insert(['code' => '001', 'name' => 'Cargador y mini cargadores', 'process_id' => '1']);
        DB::table('activities')->insert(['code' => '002', 'name' => 'Compactador de ruedas y cilindro', 'process_id' => '1']);
        DB::table('activities')->insert(['code' => '003', 'name' => 'Atendedora de asfalto (Finiere)', 'process_id' => '1']);
        DB::table('activities')->insert(['code' => '004', 'name' => 'Fresadora', 'process_id' => '1']);
        DB::table('activities')->insert(['code' => '005', 'name' => 'Densímetros nucleares', 'process_id' => '1']);
        DB::table('activities')->insert(['code' => '006', 'name' => 'Extractores de núcleos', 'process_id' => '1']);
        DB::table('activities')->insert(['code' => '007', 'name' => 'Colocación de adoquines y bordillos', 'process_id' => '1']);
        DB::table('activities')->insert(['code' => '008', 'name' => 'Empradizarían y reforestación', 'process_id' => '1']);
        DB::table('activities')->insert(['code' => '009', 'name' => 'Planta eléctrica', 'process_id' => '1']);
        DB::table('activities')->insert(['code' => '010', 'name' => 'Aplicación de la mezcla asfáltica, paleros y rastríllenlos', 'process_id' => '1']);
        DB::table('activities')->insert(['code' => '011', 'name' => 'Cortadores de ladrillo', 'process_id' => '2']);
        DB::table('activities')->insert(['code' => '012', 'name' => 'Pulidora', 'process_id' => '2']);
        DB::table('activities')->insert(['code' => '013', 'name' => 'Pluma', 'process_id' => '2']);
        DB::table('activities')->insert(['code' => '014', 'name' => 'Mampostería externa', 'process_id' => '2']);
        DB::table('activities')->insert(['code' => '015', 'name' => 'Mampostería  interna', 'process_id' => '2']);
        DB::table('activities')->insert(['code' => '016', 'name' => 'Volqueta, carro tanque', 'process_id' => '3']);
        DB::table('activities')->insert(['code' => '017', 'name' => 'Retroexcavadora, pajaritas', 'process_id' => '3']);
        DB::table('activities')->insert(['code' => '018', 'name' => 'Excavaciones (pilas-zapatas)', 'process_id' => '3']);
        DB::table('activities')->insert(['code' => '019', 'name' => 'Aseadores', 'process_id' => '3']);
        DB::table('activities')->insert(['code' => '020', 'name' => 'Empradizarían y reforestación', 'process_id' => '3']);
        DB::table('activities')->insert(['code' => '021', 'name' => 'Excavación manual', 'process_id' => '3']);
        DB::table('activities')->insert(['code' => '022', 'name' => 'Demarcación de vía', 'process_id' => '3']);
        DB::table('activities')->insert(['code' => '023', 'name' => 'Martillo Neumático', 'process_id' => '4']);
        DB::table('activities')->insert(['code' => '024', 'name' => 'Taladro', 'process_id' => '4']);
        DB::table('activities')->insert(['code' => '025', 'name' => 'Compresor', 'process_id' => '4']);
        DB::table('activities')->insert(['code' => '026', 'name' => 'Volquetas, carro tanque.', 'process_id' => '4']);
        DB::table('activities')->insert(['code' => '027', 'name' => 'Retroexcavadora, pajaritas.', 'process_id' => '4']);
        DB::table('activities')->insert(['code' => '028', 'name' => 'Cargador y Mini cargador', 'process_id' => '4']);
        DB::table('activities')->insert(['code' => '029', 'name' => 'Torre Grúa', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '030', 'name' => 'Pluma', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '031', 'name' => 'Colocación cubiertas', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '032', 'name' => 'pintura externa ', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '033', 'name' => 'pintura interna', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '034', 'name' => 'Lavado/Impermeabilización fachada', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '035', 'name' => 'Enchapes', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '036', 'name' => 'Instalación de draywall', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '037', 'name' => 'Instalación de ventanearía', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '038', 'name' => 'Planta eléctrica', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '039', 'name' => 'Concertadora, trompo, planta concretadora', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '040', 'name' => 'Bomba estacionaria y autobomba', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '041', 'name' => 'Vibrador de concreto', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '042', 'name' => 'Martillo Neumático', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '043', 'name' => 'Taladro', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '044', 'name' => 'Cortadora de ladrillo', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '045', 'name' => 'Compresor', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '046', 'name' => 'Pulidora', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '047', 'name' => 'Volquetas, carro tanque', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '048', 'name' => 'Retroexcavadora, pajaritas.', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '049', 'name' => 'Cargador y Mini cargador', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '050', 'name' => 'Camión mezclador de concreto (Mixer)', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '051', 'name' => 'Piloteadora', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '052', 'name' => 'Explosivos', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '053', 'name' => 'Afinador de piso', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '054', 'name' => 'Concretadora, trompo, planta concretadora', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '055', 'name' => 'Bomba estacionaria y autobomba', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '056', 'name' => 'Vibrador de concreto', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '057', 'name' => 'Martillo Neumático', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '058', 'name' => 'Taladro', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '059', 'name' => 'Compresor', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '060', 'name' => 'Pulidora', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '061', 'name' => 'Volquetas, carro tanque.', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '062', 'name' => 'Dumper', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '063', 'name' => 'Retroexcavadora, pajaritas.', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '064', 'name' => 'Motoniveladora', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '065', 'name' => 'Torre Grúa', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '066', 'name' => 'Compactador manual (rana, canguro)', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '067', 'name' => 'Compactador cilíndrico.', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '068', 'name' => 'Pluma', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '069', 'name' => 'Cargador y Mini cargador', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '070', 'name' => 'Camión mezclador de concreto (Mixer)', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '071', 'name' => 'Afinador de piso (helicóptero)', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '072', 'name' => 'Demarcación de vía', 'process_id' => '1']);
        DB::table('activities')->insert(['code' => '073', 'name' => 'Toma y verificación de medidas', 'process_id' => '1']);
        DB::table('activities')->insert(['code' => '074', 'name' => 'Ubicación de señalización ', 'process_id' => '1']);
        DB::table('activities')->insert(['code' => '075', 'name' => 'Detención del trafico', 'process_id' => '1']);
        DB::table('activities')->insert(['code' => '076', 'name' => 'Trabajos a borde de placa', 'process_id' => '1']);
        DB::table('activities')->insert(['code' => '077', 'name' => 'Medio de andamios y escaletas', 'process_id' => '1']);
        DB::table('activities')->insert(['code' => '078', 'name' => 'Impliquen espacios confinados', 'process_id' => '1']);
        DB::table('activities')->insert(['code' => '079', 'name' => 'Bordes de placa', 'process_id' => '1']);
        DB::table('activities')->insert(['code' => '080', 'name' => 'Inspecciones generales (EPP-Orden y aseo)', 'process_id' => '1']);
        DB::table('activities')->insert(['code' => '081', 'name' => 'Transito', 'process_id' => '1']);
        DB::table('activities')->insert(['code' => '082', 'name' => 'Ruedas con gato', 'process_id' => '1']);
        DB::table('activities')->insert(['code' => '083', 'name' => 'Manipulación de pinturas y solventes', 'process_id' => '1']);
        DB::table('activities')->insert(['code' => '084', 'name' => 'Siliconas', 'process_id' => '1']);
        DB::table('activities')->insert(['code' => '085', 'name' => 'Cambio de aceites y de filtros', 'process_id' => '1']);
        DB::table('activities')->insert(['code' => '086', 'name' => 'Colocación de aparatos tomas, rosetas', 'process_id' => '1']);
        DB::table('activities')->insert(['code' => '087', 'name' => 'Elaboración de tableros eléctricos', 'process_id' => '1']);
        DB::table('activities')->insert(['code' => '088', 'name' => 'Instalación de acometidas', 'process_id' => '1']);
        DB::table('activities')->insert(['code' => '089', 'name' => 'Arco', 'process_id' => '1']);
        DB::table('activities')->insert(['code' => '090', 'name' => 'Vacíos', 'process_id' => '1']);
        DB::table('activities')->insert(['code' => '091', 'name' => 'Corte con equipo de oxicorte', 'process_id' => '1']);
        DB::table('activities')->insert(['code' => '092', 'name' => 'Aplicación de pinturas de esmalte', 'process_id' => '1']);
        DB::table('activities')->insert(['code' => '093', 'name' => 'Aplicación de anti corrosivo', 'process_id' => '1']);
        DB::table('activities')->insert(['code' => '094', 'name' => 'Pulido de piezas - escareo de soldadura Ejemplo flejes, equipo, menores, tubería', 'process_id' => '1']);
        DB::table('activities')->insert(['code' => '095', 'name' => 'Varsol', 'process_id' => '1']);
        DB::table('activities')->insert(['code' => '096', 'name' => 'Reembase grasas', 'process_id' => '1']);
        DB::table('activities')->insert(['code' => '097', 'name' => 'Reembase ACPM', 'process_id' => '1']);
        DB::table('activities')->insert(['code' => '098', 'name' => 'Perforación Neumática', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '099', 'name' => 'Auxiliar bomba de concreto', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '100', 'name' => 'Perforación Manual', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '101', 'name' => 'Excavaciones (Pilas - Zapatas)', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '102', 'name' => 'Preparación Concreto', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '103', 'name' => 'Armado Hierro', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '104', 'name' => 'Encofrado', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '105', 'name' => 'Desencofrado', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '106', 'name' => 'Vaciado Concreto', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '107', 'name' => 'Fabricación/ Reparación Formaletas', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '108', 'name' => 'Excavación manual', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '109', 'name' => 'Instalación de draywall', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '110', 'name' => 'Perforación Neumática', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '111', 'name' => 'Planta eléctrica', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '112', 'name' => 'Perforación Neumática', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '113', 'name' => 'Auxiliar bomba de concreto', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '114', 'name' => 'Excavaciones (Pilas-Zapatas)', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '115', 'name' => 'Preparación Concreto', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '116', 'name' => 'Armado Hierro', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '117', 'name' => 'Encofrado', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '118', 'name' => 'Desencofrado', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '119', 'name' => 'Vaciado Concreto', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '120', 'name' => 'Fabricación/Reparación Formaletas', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '121', 'name' => 'Excavación manual', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '122', 'name' => 'Auxiliar producción concreto.', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '123', 'name' => 'Planta eléctrica.', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '124', 'name' => 'Toma y verificación de medidas', 'process_id' => '2']);
        DB::table('activities')->insert(['code' => '125', 'name' => 'Toma y verificación de medidas', 'process_id' => '3']);
        DB::table('activities')->insert(['code' => '126', 'name' => 'Toma y verificación de medidas', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '127', 'name' => 'Toma y verificación de medidas', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '128', 'name' => 'Toma y verificación de medidas', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '129', 'name' => 'Ubicación y verificación de medidas', 'process_id' => '3']);
        DB::table('activities')->insert(['code' => '130', 'name' => 'Detención del trafico', 'process_id' => '3']);
        DB::table('activities')->insert(['code' => '131', 'name' => 'Ubicación de señalización', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '132', 'name' => 'Detención del trafico', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '133', 'name' => 'Ingreso a excavaciones o lugares que empiquen espacios confinados', 'process_id' => '3']);
        DB::table('activities')->insert(['code' => '134', 'name' => 'Trabajos a borde de placa', 'process_id' => '2']);
        DB::table('activities')->insert(['code' => '135', 'name' => 'Acceso a niveles superiores de la obra por medio de andamios y escaleras', 'process_id' => '2']);
        DB::table('activities')->insert(['code' => '136', 'name' => 'Verificación de medidas', 'process_id' => '2']);
        DB::table('activities')->insert(['code' => '137', 'name' => 'Ingreso a excavaciones o lugares que impliquen espacios confinados', 'process_id' => '2']);
        DB::table('activities')->insert(['code' => '138', 'name' => 'Trabajos a borde de placa', 'process_id' => '4']);
        DB::table('activities')->insert(['code' => '139', 'name' => 'Acceso a niveles superiores de la obra por medio de andamios y escaleras', 'process_id' => '4']);
        DB::table('activities')->insert(['code' => '140', 'name' => 'Verificación de medidas', 'process_id' => '4']);
        DB::table('activities')->insert(['code' => '141', 'name' => 'Ingreso a excavaciones o lugares que impliquen espacios confinados', 'process_id' => '4']);
        DB::table('activities')->insert(['code' => '142', 'name' => 'Trabajos a borde de placa', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '143', 'name' => 'Acceso a niveles superiores de la obra por medio de andamios y escaleras', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '144', 'name' => 'Verificación de medidas', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '145', 'name' => 'Ingreso a excavaciones o lugares que impliquen espacios confinados', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '146', 'name' => 'Trabajos a borde de placa', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '147', 'name' => 'Acceso a niveles superiores de la obra por medio de andamios y escaleras', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '148', 'name' => 'Verificación de medidas', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '149', 'name' => 'Ingreso a excavaciones o lugares que impliquen espacios confinados', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '150', 'name' => 'Inspecciones de seguridad en lugares a bordes de placa', 'process_id' => '3']);
        DB::table('activities')->insert(['code' => '151', 'name' => 'Inspecciones generales ( epp - orden y aseo)', 'process_id' => '3']);
        DB::table('activities')->insert(['code' => '152', 'name' => 'Verificación de PMT (plan de manejo de tránsito)', 'process_id' => '3']);
        DB::table('activities')->insert(['code' => '153', 'name' => 'Inspecciones de seguridad en lugares a bordes de placa', 'process_id' => '2']);
        DB::table('activities')->insert(['code' => '154', 'name' => 'Inspecciones generales ( epp - orden y aseo)', 'process_id' => '2']);
        DB::table('activities')->insert(['code' => '155', 'name' => 'Verificación de PMT (plan de manejo de tránsito)', 'process_id' => '2']);
        DB::table('activities')->insert(['code' => '156', 'name' => 'Inspecciones de seguridad en lugares a bordes de placa', 'process_id' => '4']);
        DB::table('activities')->insert(['code' => '157', 'name' => 'Inspecciones generales ( epp - orden y aseo)', 'process_id' => '4']);
        DB::table('activities')->insert(['code' => '158', 'name' => 'Verificación de PMT (plan de manejo de tránsito)', 'process_id' => '4']);
        DB::table('activities')->insert(['code' => '159', 'name' => 'Inspecciones de seguridad en lugares a bordes de placa', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '160', 'name' => 'Inspecciones generales ( epp - orden y aseo)', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '161', 'name' => 'Verificación de PMT (plan de manejo de tránsito)', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '162', 'name' => 'Inspecciones de seguridad en lugares a bordes de placa', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '163', 'name' => 'Inspecciones generales ( epp - orden y aseo)', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '164', 'name' => 'Verificación de PMT (plan de manejo de tránsito)', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '165', 'name' => 'Inspecciones de seguridad en lugares a bordes de placa', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '166', 'name' => 'Inspecciones generales ( epp - orden y aseo)', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '167', 'name' => 'Verificación de PMT (plan de manejo de tránsito)', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '168', 'name' => 'Ingreso a la obra', 'process_id' => '3']);
        DB::table('activities')->insert(['code' => '169', 'name' => 'Recorridos de seguridad nocturnos', 'process_id' => '3']);
        DB::table('activities')->insert(['code' => '170', 'name' => 'Ubicación de la caseta de seguridad en zonas peligros', 'process_id' => '3']);
        DB::table('activities')->insert(['code' => '171', 'name' => 'Ingreso a la obra', 'process_id' => '2']);
        DB::table('activities')->insert(['code' => '172', 'name' => 'Recorridos de seguridad nocturnos', 'process_id' => '2']);
        DB::table('activities')->insert(['code' => '173', 'name' => 'Ubicación de la caseta de seguridad en zonas peligros', 'process_id' => '2']);
        DB::table('activities')->insert(['code' => '174', 'name' => 'Ingreso a la obra', 'process_id' => '4']);
        DB::table('activities')->insert(['code' => '175', 'name' => 'Recorridos de seguridad nocturnos', 'process_id' => '4']);
        DB::table('activities')->insert(['code' => '176', 'name' => 'Ubicación de la caseta de seguridad en zonas peligros', 'process_id' => '4']);
        DB::table('activities')->insert(['code' => '177', 'name' => 'Ingreso a la obra', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '178', 'name' => 'Recorridos de seguridad nocturnos', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '179', 'name' => 'Ubicación de la caseta de seguridad en zonas peligros', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '180', 'name' => 'Ingreso a la obra', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '181', 'name' => 'Recorridos de seguridad nocturnos', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '182', 'name' => 'Ubicación de la caseta de seguridad en zonas peligros', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '183', 'name' => 'Ingreso a la obra', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '184', 'name' => 'Recorridos de seguridad nocturnos', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '185', 'name' => 'Ubicación de la caseta de seguridad en zonas peligros', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '186', 'name' => 'Labores de barrido en la obra', 'process_id' => '3']);
        DB::table('activities')->insert(['code' => '187', 'name' => 'Manipulación de productos químicos (ácido nítrico - clorhídrico - fluorhídrico - Varsol)', 'process_id' => '3']);
        DB::table('activities')->insert(['code' => '188', 'name' => 'Labores de barrido en la obra', 'process_id' => '2']);
        DB::table('activities')->insert(['code' => '189', 'name' => 'Manipulación de productos químicos (ácido nítrico - clorhídrico - fluorhídrico - Varsol)', 'process_id' => '2']);
        DB::table('activities')->insert(['code' => '190', 'name' => 'Limpieza de baños', 'process_id' => '2']);
        DB::table('activities')->insert(['code' => '191', 'name' => 'Labores de barrido en la obra', 'process_id' => '4']);
        DB::table('activities')->insert(['code' => '192', 'name' => 'Limpieza de baños', 'process_id' => '4']);
        DB::table('activities')->insert(['code' => '193', 'name' => 'Labores de barrido en la obra', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '194', 'name' => 'Manipulación de productos químicos (ácido nítrico - clorhídrico - fluorhídrico - Varsol)', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '195', 'name' => 'Limpieza de ventanales', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '196', 'name' => 'Limpieza de baños', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '197', 'name' => 'Labores de barrido en la obra', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '198', 'name' => 'Manipulación de productos químicos (ácido nítrico - clorhídrico - fluorhídrico - Varsol)', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '199', 'name' => 'Limpieza de baños', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '200', 'name' => 'Labores de barrido en la obra', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '201', 'name' => 'Manipulación de productos químicos (ácido nítrico - clorhídrico - fluorhídrico - Varsol)', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '202', 'name' => 'Limpieza de ventanales', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '203', 'name' => 'Limpieza de baños', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '204', 'name' => 'Trabajos a borde de placa', 'process_id' => '2']);
        DB::table('activities')->insert(['code' => '205', 'name' => 'Acceso a niveles superiores de la obra por medio de andamios y escaleras', 'process_id' => '2']);
        DB::table('activities')->insert(['code' => '206', 'name' => 'Verificación de medidas', 'process_id' => '2']);
        DB::table('activities')->insert(['code' => '207', 'name' => 'Ingreso a excavaciones o lugares que impliquen espacios confinados', 'process_id' => '2']);
        DB::table('activities')->insert(['code' => '208', 'name' => 'Recibir y entregar materiales  por ejemplo flejes, quipos menores, tubería)', 'process_id' => '2']);
        DB::table('activities')->insert(['code' => '209', 'name' => 'Varsol', 'process_id' => '2']);
        DB::table('activities')->insert(['code' => '210', 'name' => 'Reembase de grasas', 'process_id' => '2']);
        DB::table('activities')->insert(['code' => '211', 'name' => 'Reembase  de ACPM', 'process_id' => '2']);
        DB::table('activities')->insert(['code' => '212', 'name' => 'Reembase  de pinturas vinilos', 'process_id' => '2']);
        DB::table('activities')->insert(['code' => '213', 'name' => 'Reembase de pinturas esmaltes', 'process_id' => '2']);
        DB::table('activities')->insert(['code' => '214', 'name' => 'Recibir y entregar materiales por ejemplo flejes, equipos menores, tubería Varsol.', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '215', 'name' => 'Reenbases de grasas', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '216', 'name' => 'Reenbases  de ACPM', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '217', 'name' => 'Reembase de pinturas vinilos ', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '218', 'name' => 'Reenbases de pinturas esmaltes', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '219', 'name' => 'Corte de tubos PVC o galvanizados', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '220', 'name' => 'Recibir y entregar materiales (por ejemplo flejes, quipos menores, tubería)', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '221', 'name' => 'Varsol', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '222', 'name' => 'Reembase de grasas', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '223', 'name' => 'Reembase  de ACPM', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '224', 'name' => 'Reembase  de pinturas vinilos', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '225', 'name' => 'Recibir y entregar materiales  por ejemplo flejes, quipos menores, tubería)', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '226', 'name' => 'Varsol', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '227', 'name' => 'Reembase de grasas', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '228', 'name' => 'Reembase  de ACPM', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '229', 'name' => 'Reembase  de pinturas vinilos', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '230', 'name' => 'Reembase de pinturas esmaltes', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '231', 'name' => 'Corte de tubos en PVC o galvanizado', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '232', 'name' => 'Preparación de alimentos', 'process_id' => '2']);
        DB::table('activities')->insert(['code' => '233', 'name' => 'Limpieza general de la cocina', 'process_id' => '2']);
        DB::table('activities')->insert(['code' => '234', 'name' => 'Lavado de utensilios', 'process_id' => '2']);
        DB::table('activities')->insert(['code' => '235', 'name' => 'Preparación de alimentos', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '236', 'name' => 'Limpieza general de la cocina', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '237', 'name' => 'Preparación de alimentos', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '238', 'name' => 'Limpieza general de la cocina', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '239', 'name' => 'Lavado de utensilios', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '240', 'name' => 'Preparación de alimentos', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '241', 'name' => 'Limpieza general de la cocina', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '242', 'name' => 'Lavado de utensilios', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '243', 'name' => 'Manipulación de redes de baja tensión (colocación de aparatos tomas, rosetas, cajas)', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '244', 'name' => 'Elaboración de tableros eléctricos', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '245', 'name' => 'Instalación de acometidas', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '246', 'name' => 'Manipulación de redes de baja tensión (colocación de aparatos tomas, rosetas, cajas)', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '247', 'name' => 'Elaboración de tableros eléctricos', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '248', 'name' => 'Instalación de acometidas', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '249', 'name' => 'Soldar unir piezas con soldadura eléctrica arco', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '250', 'name' => 'Soldadura en alturas o con exposición de vacíos ', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '251', 'name' => 'Corte con equipo de oxicorte', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '252', 'name' => 'Aplicación de pinturas de esmalte', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '253', 'name' => 'Aplicación de anticorrosivo', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '254', 'name' => 'Pulido de piezas-escareo de soldadura', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '255', 'name' => 'Manipulación de redes de baja tensión (colocación de aparatos tomas, rosetas, cajas)', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '256', 'name' => 'Elaboración de tableros eléctricos', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '257', 'name' => 'Instalación de acometidas', 'process_id' => '5']);
        DB::table('activities')->insert(['code' => '258', 'name' => 'Toma de muestra de concreto', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '259', 'name' => 'Pruebas para determinar la resistencia del concreto y mortero', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '260', 'name' => 'Manipulación de azufre', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '261', 'name' => 'Manipulación de superficies calientes', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '262', 'name' => 'Calentamiento de tamices', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '263', 'name' => 'Manipulación de ACPM y Gasolina en labores de limpieza', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '264', 'name' => 'Pruebas con briqueta', 'process_id' => '7']);
        DB::table('activities')->insert(['code' => '265', 'name' => 'Toma de muestra de concreto', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '266', 'name' => 'Pruebas para determinar la resistencia del concreto y mortero', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '267', 'name' => 'Manipulación de azufre', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '268', 'name' => 'Manipulación de superficies calientes', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '269', 'name' => 'Calentamiento de tamices', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '270', 'name' => 'Manipulación de ACPM y Gasolina en labores de limpieza', 'process_id' => '6']);
        DB::table('activities')->insert(['code' => '271', 'name' => 'Pruebas con briqueta', 'process_id' => '6']);

    }
}
